### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by jhrcook** [jhrcook/readgmt#1]
Need to make a logo because I definitely have the free time to do so and it is the best use of said free time.

**Comment by ghost** [comment]
Hi, @jhrcook 

If u still have interested. I have make designs for open source projects. I can make too for your. Please, give me brief about your claim.

**Comment by jhrcook** [comment]
Thank you for the offer, but it's something I actually enjoy doing (though am mediocre at best). Thank you, again, though!

**Comment by ghost** [comment]
Oh, ok. 

Good luck in process, if you need to help please write me. 

cheers. :)
